version: "3.9"

services:
  db:
    container_name: disruptions_postgres
    image: postgres
    platform: linux/amd64
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: disruptions
    ports:
      - 25432:5432
    volumes:
      - disruptions_postgres_db:/var/lib/postgresql/data
    networks:
      - disruptions_network

networks:
  disruptions_network:
    driver: bridge

volumes:
  disruptions_postgres_db:
    driver: local
