name: Create hotfix

on: workflow_dispatch

jobs:
  build:
    name: Build - ${{ github.ref_name }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Node.js and cache
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test TypeScript compiles
        run: npm run tsc:build

      - name: Test Site
        run: npm run test:site

      - name: Test SIRI-SX Generator
        run: npm run test:siri

      - name: Zip artifact
        run: zip build.zip ./* -rq

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build.zip

  create_hotfix_release:
    needs: ['build']
    name: Create hotfix release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: .

      - name: Get Latest Release
        id: latest_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: hotfix/*
          custom_tag: ${{ steps.latest_release.outputs.tag_name }}-hotfix
          tag_prefix: ''

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Hotfix ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
          files: build.zip
