name: Pull Request Merged

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js and cache
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.x'
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test TypeScript compiles
        run: npm run tsc:build

      - name: Test Site
        run: npm run test:site

      - name: Test SIRI-SX Generator
        run: npm run test:siri

      - name: Zip artifact
        run: zip build.zip ./* -rq

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build.zip

  deploy_to_test:
    needs: ['build']
    name: Deploy to Test
    runs-on: ubuntu-22.04
    environment: DISRUPTIONS_TEST
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .

      - name: Unzip artifact
        run: unzip -q build.zip

      - name: Setup Node.js and cache
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.x'
          cache: 'npm'

      - name: Rebuild npm
        run: npm rebuild

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cdd-github-actions-role-eu-west-2
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Deploy to test
        env:
          ROOT_DOMAIN: ${{ vars.ROOT_DOMAIN }}
          AWS_SES_IDENTITY_ARN: ${{ secrets.AWS_SES_TEST_IDENTITY }}
          MAP_BOX_ACCESS_TOKEN: ${{ secrets.MAP_BOX_ACCESS_TOKEN }}
        run: |
          npm run deploy -- --stage test

  deploy_to_preprod:
    needs: ['deploy_to_test']
    name: Deploy to Pre-Prod
    runs-on: ubuntu-22.04
    environment: DISRUPTIONS_PREPROD
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .

      - name: Unzip artifact
        run: unzip -q build.zip

      - name: Setup Node.js and cache
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.x'
          cache: 'npm'

      - name: Rebuild npm
        run: npm rebuild

      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cdd-github-actions-role-eu-west-2
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Deploy to pre-prod
        env:
          ROOT_DOMAIN: ${{ vars.ROOT_DOMAIN }}
          AWS_SES_IDENTITY_ARN: ${{ secrets.AWS_SES_TEST_IDENTITY }}
          MAP_BOX_ACCESS_TOKEN: ${{ secrets.MAP_BOX_ACCESS_TOKEN }}
        run: |
          npm run deploy -- --stage preprod

  create_draft_release:
    needs: ['deploy_to_preprod']
    name: Create draft release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: .

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          draft: true
          files: build.zip
