name: Pull Request Opened / Updated

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test PR
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18.14.x'
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: TypeScript Build
        run: npm run tsc:build
